<a href="https://colab.research.google.com/github/RashmiKhadka-pixel/portfolio-project/blob/main/2-core-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
 x = 7 #int
 y = 2.5 #float
 z = "2324" #str
 a = True #bool

 print(type(x), type(y), type(z), type(a))

 #casting
 print(x, y, z, a)

<class 'int'> <class 'float'> <class 'str'> <class 'bool'>
7 2.5 2324 True


In [2]:
int(x)

7

In [3]:
str(x)

'7'

In [6]:
import numpy as np

a = [True, True, False]
arr = np.array(a)
arr+1

array([2, 2, 1])

In [7]:
arr.astype(int)

array([1, 1, 0])

In [8]:
arr

array([ True,  True, False])

In [9]:
np.int64(arr)

array([1, 1, 0])

In [10]:
#EXERCISE
#Create variables a=10, b="3". Convert b to an integr and print a + int(b)

#Define variables
a = 10 #int
b = "3" #str

#print variable types
print(type(a), type(b))

#Convert variable b to integer
b = int(b)

#check type again
print(type(a), type(b))

#add variables
a+b



<class 'int'> <class 'str'>
<class 'int'> <class 'int'>


13

### You cannot add a numerical type (floats or ints) with string
###2.0 + "test" #This will be an error

In [12]:
# However we can multiply strings by integers (float doesnt work)

3 * 'test'

'testtesttest'

## IF, ELIF, AND ELSE STATEMENTS

In [13]:
def classify(x):
  if x < 0:
    return "negative"

  elif x == 0:
    return "zero"

  else:
    return "positive"

print(classify(-4), classify(8), classify(0))


negative positive zero


In [15]:
def classify(x):

  output = ""

  if x < 0:
    output = "negative"

  elif x == 0:
    output =  "zero"

  else:
    output =  "positive"

  return output

print(classify(-4), classify(8), classify(0))

negative positive zero


In [19]:
#EXERCISE Write a function is_even(n) that returns true if n is even , else False

def oddeven(x):
  if x % 2 == 0:
    return True

  else:
    return False

print(oddeven(7), oddeven(6), oddeven(68))


False True True
