<a href="https://colab.research.google.com/github/RashmiKhadka-pixel/portfolio-project/blob/main/2-core-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
 x = 7 #int
 y = 2.5 #float
 z = "2324" #str
 a = True #bool

 print(type(x), type(y), type(z), type(a))

 #casting
 print(x, y, z, a)

<class 'int'> <class 'float'> <class 'str'> <class 'bool'>
7 2.5 2324 True


In [2]:
int(x)

7

In [3]:
str(x)

'7'

In [6]:
import numpy as np

a = [True, True, False]
arr = np.array(a)
arr+1

array([2, 2, 1])

In [7]:
arr.astype(int)

array([1, 1, 0])

In [8]:
arr

array([ True,  True, False])

In [9]:
np.int64(arr)

array([1, 1, 0])

In [10]:
#EXERCISE
#Create variables a=10, b="3". Convert b to an integr and print a + int(b)

#Define variables
a = 10 #int
b = "3" #str

#print variable types
print(type(a), type(b))

#Convert variable b to integer
b = int(b)

#check type again
print(type(a), type(b))

#add variables
a+b



<class 'int'> <class 'str'>
<class 'int'> <class 'int'>


13

### You cannot add a numerical type (floats or ints) with string
###2.0 + "test" #This will be an error

In [12]:
# However we can multiply strings by integers (float doesnt work)

3 * 'test'

'testtesttest'

## IF, ELIF, AND ELSE STATEMENTS

In [13]:
def classify(x):
  if x < 0:
    return "negative"

  elif x == 0:
    return "zero"

  else:
    return "positive"

print(classify(-4), classify(8), classify(0))


negative positive zero


In [15]:
def classify(x):

  output = ""

  if x < 0:
    output = "negative"

  elif x == 0:
    output =  "zero"

  else:
    output =  "positive"

  return output

print(classify(-4), classify(8), classify(0))

negative positive zero


In [19]:
#EXERCISE Write a function is_even(n) that returns true if n is even , else False

#Define function
def oddeven(x):
  if x % 2 == 0:
    return True

  else:
    return False

#Test function
print(oddeven(7), oddeven(6), oddeven(68))


False True True


In [20]:
oddeven(0)

True

In [21]:
oddeven(-9.1)

False

##Loops: for and while

$$\sum_{i=1}^n i = \frac{n(n+1)}{2}$$

In [31]:
100*(100+1)/2

5050.0

In [32]:
integer_list =[]

for i in range (1, 101):
  integer_list.append(i)

print(integer_list)
print(sum(integer_list))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
5050


In [28]:

for i in range(5):
  print(i*3)

0
3
6
9
12


In [23]:
even_numbers = [0, 2, 4, 6, 8, 10]

for n in even_numbers:
  print(n)

0
2
4
6
8
10


In [34]:
# for
s = 0
for k in range(101):  #k = 0,...,100
  s += k
print("sum 0,....100:", s)


sum 0,....100: 5050
