<a href="https://colab.research.google.com/github/RashmiKhadka-pixel/portfolio-project/blob/main/2-core-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
 x = 7 #int
 y = 2.5 #float
 z = "2324" #str
 a = True #bool

 print(type(x), type(y), type(z), type(a))

 #casting
 print(x, y, z, a)

<class 'int'> <class 'float'> <class 'str'> <class 'bool'>
7 2.5 2324 True


In [2]:
int(x)

7

In [3]:
str(x)

'7'

In [6]:
import numpy as np

a = [True, True, False]
arr = np.array(a)
arr+1

array([2, 2, 1])

In [7]:
arr.astype(int)

array([1, 1, 0])

In [8]:
arr

array([ True,  True, False])

In [9]:
np.int64(arr)

array([1, 1, 0])

In [10]:
#EXERCISE
#Create variables a=10, b="3". Convert b to an integr and print a + int(b)

a = 10 #int
b = "3" #str

print(type(a), type(b))

b = int(b)

print(type(a), type(b))

a+b



<class 'int'> <class 'str'>
<class 'int'> <class 'int'>


13